-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UserEating.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import UserEating.InputObject
import UserEating.Interface
import UserEating.Object
import UserEating.Scalar
import UserEating.ScalarCodecs
import UserEating.Union


created_at : SelectionSet (Maybe String) UserEating.Object.User
created_at =
    Object.selectionForField "(Maybe String)" "created_at" [] (Decode.string |> Decode.nullable)


email : SelectionSet (Maybe String) UserEating.Object.User
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


first_name : SelectionSet (Maybe String) UserEating.Object.User
first_name =
    Object.selectionForField "(Maybe String)" "first_name" [] (Decode.string |> Decode.nullable)


id : SelectionSet String UserEating.Object.User
id =
    Object.selectionForField "String" "id" [] Decode.string


last_name : SelectionSet (Maybe String) UserEating.Object.User
last_name =
    Object.selectionForField "(Maybe String)" "last_name" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe String) UserEating.Object.User
updated_at =
    Object.selectionForField "(Maybe String)" "updated_at" [] (Decode.string |> Decode.nullable)
