-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UserEating.Object exposing (..)


type SubscribedQuery
    = SubscribedQuery


type User
    = User


type UserStatus
    = UserStatus


type WebsocketConnection
    = WebsocketConnection
