-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UserEating.Object exposing (..)


type Eating
    = Eating


type Sleeping
    = Sleeping


type SubscribedQuery
    = SubscribedQuery


type User
    = User


type WebsocketConnection
    = WebsocketConnection
